name: fiap-fase3

services:
  postgres:
    image: postgres:18
    container_name: postgres-fase3

    environment:
      TZ: America/Sao_Paulo

      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "8745:5432"

    volumes:
      - postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_NAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always

    networks:
      - shared-net

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-fase3

    environment:
      TZ: America/Sao_Paulo

      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-fiap}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always

    networks:
      - shared-net

volumes:
  postgres-data:
    name: fiap-postgres-data

  rabbitmq-data:
    name: fiap-rabbitmq-data

networks:
  shared-net:
    name: shared-net
